### ISSUE TITLE
I have occasional crash problems.

### ISSUE THREAD

**Issue by OverBrave** [BentoBoxWorld/CaveBlock#11]
#### Description
I tried 16 players together. In uncertain times I usually get the error on the server when creating the cave.

#### Expected behavior
Correction of crash problems.

#### Server Information:
 - Database being used (YAML, JSON, MySQL, MongoDB): YAML
 - OS: Linux
 - Java Version: Java 8
 - BentoBox version: 1.2.1

**Comment by BONNe** [comment]
Pls, can you provide crash log, `bentobox v` message and plugin list.

**Comment by OverBrave** [comment]
I have 2 crash report.
https://paste.ee/p/NjGj5
https://paste.ee/p/i0SP1
![image](https://user-images.githubusercontent.com/47111280/52196203-02333480-286c-11e9-9f08-47745b72b4cf.png)

**Comment by tastybento** [comment]
Do these crashed happen when players going to the end, (as mentioned on Discord)?

@BONNe If so, then it may be caused by the server not being able to find a place to stick the end exit island and going into an infinite loop. If that's the case, then the 1.3.0 build with the fix I did for end exit island may help (maybe). Or your end generator may need to make the chunks around 0,0 clear from 250 and above.

**Comment by BONNe** [comment]
Hmm... for me, it just put it in the top and invalidate, but did not crash a server.
But I will try to get rid of it.

**Comment by BONNe** [comment]
@OverBrave , you could try to lower world height (f.e. 250 or 240) and regenerate cave block worlds.
You can do it by changing world-depth in caveblock config.

**Comment by OverBrave** [comment]
Same problem its continues

**Comment by tastybento** [comment]
@OverBrave Can you try this version of Caveblock and see if it helps?
[caveblock-0.1.0.jar.zip](https://github.com/BentoBoxWorld/CaveBlock/files/2835265/caveblock-0.1.0.jar.zip)

@BONNe  I just make a version that makes a hole around 0,0 for chunks so the end exit island can be placed. This is to test to see if the crash is caused by an infinite loop search for a spot to place the island.

**Comment by OverBrave** [comment]
Again crashed.

**Comment by tastybento** [comment]
You will need to stop the server, delete the Cave End World  completely and then try it. Did you delete the world before testing?

**Comment by OverBrave** [comment]
Yes.

**Comment by tastybento** [comment]
Can you share your console log from the last crash?

**Comment by OverBrave** [comment]
[latest.log](https://github.com/BentoBoxWorld/CaveBlock/files/2835320/latest.log)

**Comment by tastybento** [comment]
That is far more useful. I was barking up the wrong tree. Thanks. Investigating.

**Comment by tastybento** [comment]
Work around should be to remove the NETHER_BRICK and CHORUS_FRUIT entries from the config.yml and any other materials mentioned in the console log errors. 

- MATERIAL:NETHER_BRICK:10:5
- MATERIAL:CHORUS_FRUIT:1:3

It seems the populator is having an issue setting those blocks. It's random because they are chosen at random.

Need to work out why, but it's past midnight, so another day! Or maybe @BONNe can work it out.

**Comment by tastybento** [comment]
Found the issue. Fixing now.

**Comment by robert-beckley** [comment]
I know this was closed and i should make my own ticket but im still having the issue and i never had thoese materials in the list. i wil try and get a crashlog now but the way the server crashes it does not make a log.

**Comment by tastybento** [comment]
@robert-beckley Yes, please do that.
