### ISSUE TITLE
Suggestions and mistakes

### ISSUE THREAD

**Issue by Kaczuc** [BentoBoxWorld/CaveBlock#29]
- when storing through the portal to the end there is an error: https://pastebin.com/NB5sXgFB

- Possibility to change the name of rank / addition which deletion is about Krola of Dwarf

- Translation option /cb settings

- Automatic update of the add-in after entering the command and creating a backup to the .zip / .rar file

- Possibility to add your own schemes for normal world, nether, end

- The option to set another increases by default after creating the cave

- Error with displaying the version of the plugin 
![image](https://user-images.githubusercontent.com/43011737/59563042-01d65180-9035-11e9-9a77-216b4560eb83.png)

**Comment by BONNe** [comment]
Better is to create new issue request for each problem as otherwise, it is hard to manage missing parts.

> when storing through the portal to the end there is an error: https://pastebin.com/NB5sXgFB

About crash: Fixed in BentoBox 1.5.2 release

> Possibility to change the name of rank / addition which deletion is about Krola of Dwarf

Rank names can be edited in /plugins/BentoBox/locales/CaveBlock file. 
Unfortunately, rank adding/removing is not possible for now.

> Translation option /cb settings

The translation is managed by BentoBox. (/bentobox manage)

> Automatic update of the add-in after entering the command and creating a backup to the .zip / .rar file

Automatic updating is not implemented yet. It will be done by BentoBox

> Possibility to add your own schemes for normal world, nether, end

BluePrints (schems) are possible to add already. Use /cba bp and /bentobox manage

> The option to set another increases by default after creating the cave

Sorry, did not understand what you mean with it.

> The option to set another increases by default after creating the cave

Will be fixed in next build. 


I answered on these questions/suggestions, but please, create a separate issue for each problem/suggestion.
