### ISSUE TITLE
Cave in the End has the biomes 'nether_waste' and ghast, pigman is spawning there

### ISSUE THREAD

**Issue by Clavellina** [BentoBoxWorld/CaveBlock#54]
### Description
I don't know if this is a 'bug' or not. However, when I went to 'End World' in the caveblock there was a ghast and pigman that spawning. When I check the 'F3' to check the biome it says 'Nether_wastes' althought i've set the biome is 'The End', what should I do?

![image](https://user-images.githubusercontent.com/76399063/102716704-20936380-4310-11eb-8be7-bfbfb379d495.png)

![image](https://user-images.githubusercontent.com/76399063/102716708-2a1ccb80-4310-11eb-8467-7a3d147f4a0d.png)

![image](https://user-images.githubusercontent.com/76399063/102716714-33a63380-4310-11eb-8c51-4e345d019506.png)

**Comment by tastybento** [comment]
The bug was in the CaveBlock addon. I'll do another release to fix this, then you can get the new version.

**Comment by tastybento** [comment]
https://github.com/BentoBoxWorld/CaveBlock/releases/tag/1.14.2

Unfortunately, you will need to delete your end world and let it recreate, or accept that the blocks generated so far will have Nether biome.

If you delete your End World and have players already on your server, then change this part of the Cave Block config.yml to true so that missing end islands will be pasted:

```
# Create Nether or End cave if they are missing when a player goes through a portal.
  # Nether and End cave are usually pasted when a player makes their cave, but if they are
  # missing for some reason, you can switch this on.
  # Note that bedrock removal glitches can exploit this option.
  # Added since 1.10.0.
  create-missing-nether-end-caves: true
```
