### ISSUE TITLE
nether spawn all monster by spawner it can't attack player active

### ISSUE THREAD

**Issue by DongShaoNB** [BentoBoxWorld/CaveBlock#83]
### Expected behavior

nether spawn all monster by spawner it can attack player active

### Observed/Actual behavior

nether spawn all monster by spawner it can't attack player active, it seems that there is no AI, but use spawnegg spawn a monster it can attack player

### Steps/models to reproduce

teleport to caveblock nether, wait to spawn monster by spawner

### BentoBox version

Running  MIRAI 1.19.2
BentoBox version： 1.21.1
Database： MYSQL
Loaded Game Worlds：
caveblock-world (CaveBlock) : Overworld, Nether, The End
Loaded Addons：
Biomes 2.0.0 (ENABLED)
Border 3.2.0 (ENABLED)
CaveBlock 1.16.0 (ENABLED)
ControlPanel 1.13.0 (ENABLED)
DimensionalTrees 1.6.0 (ENABLED)
Level 2.9.0 (ENABLED)
Likes 2.3.0 (ENABLED)
Limits 1.19.0 (ENABLED)
MagicCobblestoneGenerator 2.4.0 (ENABLED)
Warps 1.12.0 (ENABLED)

### Plugin list

LevelledMobs 3.8.0 b716
BloodNight 0.11.1-DEV+06c0250

**Comment by BONNe** [comment]
BentoBox does not distinguish mobs spawned from spawners, spawneggs and natural spawning. 

All mobs have the same behavior:
- they attack all players above visitor rank
- they atack visitors if visitor protection is disabled
- they will not target visitors if visitor protection is enabled.

As you have issue with spawners, I suspect that the issue is with one of your plugins. Probably it is not configured correctly.
Maybe they require to specify some settings in config.

**Comment by DongShaoNB** [comment]
> BentoBox does not distinguish mobs spawned from spawners, spawneggs and natural spawning.
> 
> All mobs have the same behavior:
> 
> * they attack all players above visitor rank
> * they atack visitors if visitor protection is disabled
> * they will not target visitors if visitor protection is enabled.
> 
> As you have issue with spawners, I suspect that the issue is with one of your plugins. Probably it is not configured correctly. Maybe they require to specify some settings in config.

ok, thank you
